# Generated by Django 3.1.7 on 2021-03-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='service_provider',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
