# Generated by Django 3.1.7 on 2021-03-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_service_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='service_provider',
            field=models.CharField(blank=True, choices=[('--None--', 'none'), ('Sprint', 'sprint'), ('Verizon', 'verizon'), ('AT&T', 'att'), ('T-Mobile', 'tmobile')], max_length=20),
        ),
    ]
