# Generated by Django 3.1.7 on 2021-03-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210312_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='service_provider',
            field=models.CharField(choices=[('--None--', 'none'), ('Sprint', 'sprint'), ('Verizon', 'verizon'), ('AT&T', 'att'), ('T-Mobile', 'tmobile')], default='none', max_length=20),
        ),
    ]
